language: ruby
os: linux

services:
  - postgresql

cache:
  bundler: true
  directories:
    - node_modules  

jobs:
  include:
    - stage: Unit Tests
      install:
        - yarn install
        - bundle install --without production
      before_script:
        - cp config/database.travis.yml config/database.yml # update the db config to the travis-ci specific db config
        - psql -c 'create database travis_ci_test;' -U postgres # create the db
      script:
        - bundle exec rails db:migrate
        - bundle exec rails test
    - stage: Deployment
      #if: branch = master #only deploy from master
      install: skip
      script: skip
      deploy:
        provider: heroku
        app: students-toolshed-staging
        api_key:
          secure: "iTVgGEOhKksc3jgUm4LiCA0KnTAnL+tHdfVnPT8qYHW8KeE9lfJ2ItatCGp1zbzzkNrwTxTKn9pOtw2NkZu+Ml7mlpSx5xB7fPah/cCQSdY8qLH6hWrt3sSrEDo5VlOpHrix1g+yz/JQsfsabtyECiiRV0TXOFDvOZbvS9/nz6peoh6RmWVs51jKaPfeI5eX5eCYLpFcD9Xis4a7PUN9yUYtCa13+kpZ6Uw+EYIwg+1zhZHOY1iRv2chEtIn4iCYFJ9cYSWIs80XBMDMK0zCTvkK2XBkwBWiSHvc8knbTIPK487kapWH0Tq4y5oEp2bFqpAtDcI+mqBT7pkkH+ms+XROF4mTel2IvbHrqV1CI3nlgjhEmesH/JBMmMIx0p0UU09zq+pIHig+/PPOzcZ3DWWrN5jLxxYGHsBy6dhU1IvZUyAB8LZpnV6AQEclIxrKBhWNAUJxkjD9A8CHN0r1csoFIfTONhNIs/x7CDY1Zd0MGmoDZC8YFhwoTo+PPTS04Cy+3MlbdpqXtsOUs0Zlw+WakzvXLbDwNYs34S/rP/2sp3lLlzmebWcw9rQlNURQiVkQdGROmZB6szjLOHJqRpCfunlPg3/cg3TXwHLOMnBVv9YkdD0S9jKLM2Rfymspyo7522k9wqV3z8dA2ozvtemX0I++xSBEBO3F2Amb0ok="
