services:
  - docker
  
jobs:
  include:
    - stage: Tests
      install: 
        - docker-compose build
        - docker-compose run app rails db:create
        - docker-compose run app rails db:migrate
      script: docker-compose run app rails test
