language: ruby
os: linux

services:
  - postgresql

cache:
  bundler: true
  directories:
    - node_modules  

jobs:
  include:
    - stage: Tests
      install:
        - yarn install
        - bundle install --without production
      before_script:
        - cp config/database.travis.yml config/database.yml # setup the travis-ci specific db config
        - bundle exec rails db:migrate
      script: bundle exec rails test
