language: ruby

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run app rails db:create
  - docker-compose run app rails db:migrate

jobs:
  include:
    - stage: Tests
      script: docker-compose run app rails test
