language: ruby
os: linux
cache:
  bundler: true
  directories:
  - node_modules

before_install: &common_build
  - yarn install
  - bundle install --without production

jobs:
  include:
    - stage: Tests
      install: skip
      script: bundle exec rails test
