language: ruby
os: linux
cache:
  bundler: true
  directories:
    - node_modules  

jobs:
  include:
    - stage: Tests
      install:
        - yarn install
        - bundle install --without production
      script: bundle exec rails test
