app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  # ignore these directories when mounting the volume
    - /app/node_modules
    - /app/tmp/pids/
  ports:
    - "3000:3000"
  links:
    - database
database:
  image: postgres:12.0
  ports:
    - "5432"