name: CI
on: [push]
jobs:
  Build and Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Image
        run: docker-compose build
      - name: Run Tests
        run: docker-compose run app rails test
